import { WorshipSong } from '@/types/songs';

export const MOCK_SONGS: WorshipSong[] = [
  {
    id: '1',
    title: 'Holy Forever',
    artist: 'Chris Tomlin',
    songwriter: 'Chris Tomlin, Phil Wickham, Brian Johnson, Jenn Johnson, Jason Ingram',
    defaultKey: 'G',
    bpm: 72,
    timeSignature: '4/4',
    language: 'English',
    themes: ['Grace', 'Holiness', 'God\'s Faithfulness'],
    scriptureReferences: ['Revelation 4:8', 'Isaiah 6:3'],
    songType: 'Worship',
    status: 'Active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'King of Kings',
    artist: 'Hillsong Worship',
    songwriter: 'Brooke Ligertwood, Jason Ingram, Scott Ligertwood',
    defaultKey: 'D',
    bpm: 68,
    timeSignature: '4/4',
    language: 'English',
    themes: ['Resurrection', 'Gospel', 'Salvation'],
    scriptureReferences: ['1 Corinthians 15:57', 'Revelation 19:16'],
    songType: 'Praise',
    status: 'Active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Great Are You Lord',
    artist: 'All Sons & Daughters',
    songwriter: 'David Leonard, Jason Ingram, Leslie Jordan',
    defaultKey: 'A',
    bpm: 72,
    timeSignature: '6/8',
    language: 'English',
    themes: ['Praise', 'Faith', 'Surrender'],
    scriptureReferences: ['Psalm 145:3', 'Ezekiel 37:9'],
    songType: 'Worship',
    status: 'Active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Purihin ang Panginoon',
    artist: 'Traditional',
    defaultKey: 'C',
    bpm: 100,
    timeSignature: '4/4',
    language: 'Filipino/Tagalog',
    themes: ['Praise', 'Thanksgiving'],
    scriptureReferences: ['Psalm 100'],
    songType: 'Opening',
    status: 'Active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
