/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicMediaRouteImport } from './routes/_public/media'
import { Route as PublicResourcesRouteImport } from './routes/_public/resources'
import { Route as PublicSongsRouteImport } from './routes/_public/songs'
import { Route as PublicTeamRouteImport } from './routes/_public/team'
import { Route as PublicWorshipRouteImport } from './routes/_public/worship'
import { Route as AuthenticatedMediaUploadRouteImport } from './routes/_authenticated/media/upload'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated/team/index'
import { Route as PublicResourcesIdRouteImport } from './routes/_public/resources.$id'
import { Route as PublicSetlistsIndexRouteImport } from './routes/_public/setlists/index'
import { Route as PublicSetlistsIdRouteImport } from './routes/_public/setlists/$id'
import { Route as PublicSongsIndexRouteImport } from './routes/_public/songs/index'
import { Route as PublicSongsIdRouteImport } from './routes/_public/songs/$id'
import { Route as PublicTeamIdRouteImport } from './routes/_public/team.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMediaRoute = PublicMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResourcesRoute = PublicResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSongsRoute = PublicSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTeamRoute = PublicTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWorshipRoute = PublicWorshipRouteImport.update({
  id: '/worship',
  path: '/worship',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedMediaUploadRoute =
  AuthenticatedMediaUploadRouteImport.update({
    id: '/media/upload',
    path: '/media/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicResourcesIdRoute = PublicResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicResourcesRoute,
} as any)
const PublicSetlistsIndexRoute = PublicSetlistsIndexRouteImport.update({
  id: '/setlists/',
  path: '/setlists/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSetlistsIdRoute = PublicSetlistsIdRouteImport.update({
  id: '/setlists/$id',
  path: '/setlists/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSongsIndexRoute = PublicSongsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicSongsRoute,
} as any)
const PublicSongsIdRoute = PublicSongsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicSongsRoute,
} as any)
const PublicTeamIdRoute = PublicTeamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicTeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/login': typeof PublicLoginRoute
  '/media': typeof PublicMediaRoute
  '/resources': typeof PublicResourcesRouteWithChildren
  '/songs': typeof PublicSongsRouteWithChildren
  '/team': typeof PublicTeamRouteWithChildren
  '/worship': typeof PublicWorshipRoute
  '/media/upload': typeof AuthenticatedMediaUploadRoute
  '/resources/$id': typeof PublicResourcesIdRoute
  '/setlists/$id': typeof PublicSetlistsIdRoute
  '/songs/$id': typeof PublicSongsIdRoute
  '/team/$id': typeof PublicTeamIdRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
  '/setlists/': typeof PublicSetlistsIndexRoute
  '/songs/': typeof PublicSongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/login': typeof PublicLoginRoute
  '/media': typeof PublicMediaRoute
  '/resources': typeof PublicResourcesRouteWithChildren
  '/team': typeof AuthenticatedTeamIndexRoute
  '/worship': typeof PublicWorshipRoute
  '/media/upload': typeof AuthenticatedMediaUploadRoute
  '/resources/$id': typeof PublicResourcesIdRoute
  '/setlists/$id': typeof PublicSetlistsIdRoute
  '/songs/$id': typeof PublicSongsIdRoute
  '/team/$id': typeof PublicTeamIdRoute
  '/setlists': typeof PublicSetlistsIndexRoute
  '/songs': typeof PublicSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/media': typeof PublicMediaRoute
  '/_public/resources': typeof PublicResourcesRouteWithChildren
  '/_public/songs': typeof PublicSongsRouteWithChildren
  '/_public/team': typeof PublicTeamRouteWithChildren
  '/_public/worship': typeof PublicWorshipRoute
  '/_authenticated/media/upload': typeof AuthenticatedMediaUploadRoute
  '/_public/resources/$id': typeof PublicResourcesIdRoute
  '/_public/setlists/$id': typeof PublicSetlistsIdRoute
  '/_public/songs/$id': typeof PublicSongsIdRoute
  '/_public/team/$id': typeof PublicTeamIdRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
  '/_public/setlists/': typeof PublicSetlistsIndexRoute
  '/_public/songs/': typeof PublicSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/login'
    | '/media'
    | '/resources'
    | '/songs'
    | '/team'
    | '/worship'
    | '/media/upload'
    | '/resources/$id'
    | '/setlists/$id'
    | '/songs/$id'
    | '/team/$id'
    | '/team/'
    | '/setlists/'
    | '/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/login'
    | '/media'
    | '/resources'
    | '/team'
    | '/worship'
    | '/media/upload'
    | '/resources/$id'
    | '/setlists/$id'
    | '/songs/$id'
    | '/team/$id'
    | '/setlists'
    | '/songs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/login'
    | '/_public/media'
    | '/_public/resources'
    | '/_public/songs'
    | '/_public/team'
    | '/_public/worship'
    | '/_authenticated/media/upload'
    | '/_public/resources/$id'
    | '/_public/setlists/$id'
    | '/_public/songs/$id'
    | '/_public/team/$id'
    | '/_authenticated/team/'
    | '/_public/setlists/'
    | '/_public/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/media': {
      id: '/_public/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof PublicMediaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/resources': {
      id: '/_public/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof PublicResourcesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/songs': {
      id: '/_public/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof PublicSongsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/team': {
      id: '/_public/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof PublicTeamRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/worship': {
      id: '/_public/worship'
      path: '/worship'
      fullPath: '/worship'
      preLoaderRoute: typeof PublicWorshipRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/media/upload': {
      id: '/_authenticated/media/upload'
      path: '/media/upload'
      fullPath: '/media/upload'
      preLoaderRoute: typeof AuthenticatedMediaUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/resources/$id': {
      id: '/_public/resources/$id'
      path: '/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof PublicResourcesIdRouteImport
      parentRoute: typeof PublicResourcesRoute
    }
    '/_public/setlists/': {
      id: '/_public/setlists/'
      path: '/setlists'
      fullPath: '/setlists/'
      preLoaderRoute: typeof PublicSetlistsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/setlists/$id': {
      id: '/_public/setlists/$id'
      path: '/setlists/$id'
      fullPath: '/setlists/$id'
      preLoaderRoute: typeof PublicSetlistsIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/songs/': {
      id: '/_public/songs/'
      path: '/'
      fullPath: '/songs/'
      preLoaderRoute: typeof PublicSongsIndexRouteImport
      parentRoute: typeof PublicSongsRoute
    }
    '/_public/songs/$id': {
      id: '/_public/songs/$id'
      path: '/$id'
      fullPath: '/songs/$id'
      preLoaderRoute: typeof PublicSongsIdRouteImport
      parentRoute: typeof PublicSongsRoute
    }
    '/_public/team/$id': {
      id: '/_public/team/$id'
      path: '/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof PublicTeamIdRouteImport
      parentRoute: typeof PublicTeamRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMediaUploadRoute: typeof AuthenticatedMediaUploadRoute
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMediaUploadRoute: AuthenticatedMediaUploadRoute,
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicResourcesRouteChildren {
  PublicResourcesIdRoute: typeof PublicResourcesIdRoute
}

const PublicResourcesRouteChildren: PublicResourcesRouteChildren = {
  PublicResourcesIdRoute: PublicResourcesIdRoute,
}

const PublicResourcesRouteWithChildren = PublicResourcesRoute._addFileChildren(
  PublicResourcesRouteChildren,
)

interface PublicSongsRouteChildren {
  PublicSongsIdRoute: typeof PublicSongsIdRoute
  PublicSongsIndexRoute: typeof PublicSongsIndexRoute
}

const PublicSongsRouteChildren: PublicSongsRouteChildren = {
  PublicSongsIdRoute: PublicSongsIdRoute,
  PublicSongsIndexRoute: PublicSongsIndexRoute,
}

const PublicSongsRouteWithChildren = PublicSongsRoute._addFileChildren(
  PublicSongsRouteChildren,
)

interface PublicTeamRouteChildren {
  PublicTeamIdRoute: typeof PublicTeamIdRoute
}

const PublicTeamRouteChildren: PublicTeamRouteChildren = {
  PublicTeamIdRoute: PublicTeamIdRoute,
}

const PublicTeamRouteWithChildren = PublicTeamRoute._addFileChildren(
  PublicTeamRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicMediaRoute: typeof PublicMediaRoute
  PublicResourcesRoute: typeof PublicResourcesRouteWithChildren
  PublicSongsRoute: typeof PublicSongsRouteWithChildren
  PublicTeamRoute: typeof PublicTeamRouteWithChildren
  PublicWorshipRoute: typeof PublicWorshipRoute
  PublicSetlistsIdRoute: typeof PublicSetlistsIdRoute
  PublicSetlistsIndexRoute: typeof PublicSetlistsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicMediaRoute: PublicMediaRoute,
  PublicResourcesRoute: PublicResourcesRouteWithChildren,
  PublicSongsRoute: PublicSongsRouteWithChildren,
  PublicTeamRoute: PublicTeamRouteWithChildren,
  PublicWorshipRoute: PublicWorshipRoute,
  PublicSetlistsIdRoute: PublicSetlistsIdRoute,
  PublicSetlistsIndexRoute: PublicSetlistsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
